// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | AbsSlice
  | ResultsSlice
  | LogoCarouselSlice
  | CtaSlice
  | QuestionsSlice
  | HeroSlice;

/**
 * Item in *Page → Structured Data*
 */
export interface PageDocumentDataStructuredDataItem {
  /**
   * JSON field in *Page → Structured Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.structured_data[].json
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  json: prismic.KeyTextField;
}

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Search Summary field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This is used only for site search
   * - **API ID Path**: page.search_summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_summary: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * OG Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left empty, meta title will be used
   * - **API ID Path**: page.og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OG Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left empty, meta description will be used
   * - **API ID Path**: page.og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * OG URL field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left empty, default page URL will be used
   * - **API ID Path**: page.og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_url: prismic.KeyTextField; /**
   * Structured Data field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.structured_data[]
   * - **Tab**: Structured Data
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  structured_data: prismic.GroupField<
    Simplify<PageDocumentDataStructuredDataItem>
  >;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Contact Us*
 */
export interface SettingsDocumentDataContactUsItem {
  /**
   * Label field in *Settings → Contact Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * Icon Name field in *Settings → Contact Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;
}

/**
 * Item in *Settings → Repeatable Types*
 */
export interface SettingsDocumentDataRepeatableTypesItem {
  /**
   * Type field in *Settings → Repeatable Types*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The exact name of the page type
   * - **API ID Path**: settings.repeatable_types[].type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  type: prismic.KeyTextField;

  /**
   * Items per page field in *Settings → Repeatable Types*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_types[].items_per_page
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  items_per_page: prismic.NumberField;

  /**
   * Listing Page field in *Settings → Repeatable Types*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_types[].listing_page
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  listing_page: ContentRelationshipFieldWithData<
    [
      {
        id: "page";
        fields: [
          {
            id: "parent";
            customtypes: [{ id: "page"; fields: ["parent", "title"] }];
          },
          "title",
        ];
      },
    ]
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  siteTitle: prismic.RichTextField;

  /**
   * Header Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * Footer Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * GTM Code field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.gtm_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gtm_code: prismic.KeyTextField;

  /**
   * Copyright Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;

  /**
   * Footer Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_description: prismic.KeyTextField; /**
   * Social Profiles field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_profiles
   * - **Tab**: Social Profiles
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_profiles: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      | "X (Twitter)"
      | "Facebook"
      | "LinkedIn"
      | "Instagram"
      | "TikTok"
      | "YouTube"
    >
  >; /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: Default Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Default Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField; /**
   * Contact Us Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us_title
   * - **Tab**: Contact Details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_us_title: prismic.RichTextField;

  /**
   * Contact Us field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us[]
   * - **Tab**: Contact Details
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_us: prismic.GroupField<
    Simplify<SettingsDocumentDataContactUsItem>
  >; /**
   * Repeatable Types field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_types[]
   * - **Tab**: Repeatable Types
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatable_types: prismic.GroupField<
    Simplify<SettingsDocumentDataRepeatableTypesItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *Abs → Default → Primary → Tiles*
 */
export interface AbsSliceDefaultPrimaryTilesItem {
  /**
   * Label field in *Abs → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.tiles[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Title field in *Abs → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.tiles[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Abs → Default → Primary → Tiles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.tiles[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Abs → Default → Primary → Buttons*
 */
export interface AbsSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Abs → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Variant field in *Abs → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary" | "Link">;
}

/**
 * Primary content in *Abs → Default → Primary*
 */
export interface AbsSliceDefaultPrimary {
  /**
   * With divider field in *Abs → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: abs.default.primary.with_border
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_border: prismic.BooleanField;

  /**
   * No background field in *Abs → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: abs.default.primary.no_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  no_background: prismic.BooleanField;

  /**
   * Top Padding field in *Abs → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Abs → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Caption field in *Abs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Title field in *Abs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Abs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Tiles field in *Abs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.tiles[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tiles: prismic.GroupField<Simplify<AbsSliceDefaultPrimaryTilesItem>>;

  /**
   * Buttons field in *Abs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: abs.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<AbsSliceDefaultPrimaryButtonsItem>>;
}

/**
 * Default variation for Abs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AbsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AbsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Abs*
 */
type AbsSliceVariation = AbsSliceDefault;

/**
 * Abs Shared Slice
 *
 * - **API ID**: `abs`
 * - **Description**: Abs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AbsSlice = prismic.SharedSlice<"abs", AbsSliceVariation>;

/**
 * Item in *Cta → Default → Primary → Buttons*
 */
export interface CtaSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon Name field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * Icon Alignment  field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].icon_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_alignment: prismic.SelectField<"Left" | "Right">;

  /**
   * Variant field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary">;
}

/**
 * Item in *Cta → Full Width → Primary → Buttons*
 */
export interface CtaSliceFullWidthPrimaryButtonsItem {
  /**
   * Link field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon Name field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * Icon Alignment  field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].icon_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_alignment: prismic.SelectField<"Left" | "Right">;

  /**
   * Variant field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary">;
}

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Top Padding field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * With Background Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cta.default.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<CtaSliceDefaultPrimaryButtonsItem>>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Full Width → Primary*
 */
export interface CtaSliceFullWidthPrimary {
  /**
   * Top Padding field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Title field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<CtaSliceFullWidthPrimaryButtonsItem>>;
}

/**
 * Full Width variation for Cta Slice
 *
 * - **API ID**: `fullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceFullWidth = prismic.SharedSliceVariation<
  "fullWidth",
  Simplify<CtaSliceFullWidthPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceFullWidth;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Variant field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary" | "Link">;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Top Padding field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Caption field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Text align left field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.text_align_left
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  text_align_left: prismic.BooleanField;

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;

  /**
   * CTA Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_description: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *LogoCarousel → Default → Primary → Images*
 */
export interface LogoCarouselSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *LogoCarousel → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoCarousel → Default → Primary*
 */
export interface LogoCarouselSliceDefaultPrimary {
  /**
   * With divider field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_carousel.default.primary.with_border
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_border: prismic.BooleanField;

  /**
   * No background field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_carousel.default.primary.no_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  no_background: prismic.BooleanField;

  /**
   * Top Padding field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: logo_carousel.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"None" | "Half" | "Full", "filled">;

  /**
   * Bottom Padding field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: None
   * - **API ID Path**: logo_carousel.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"None" | "Half" | "Full", "filled">;

  /**
   * Title field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Images field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<LogoCarouselSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for LogoCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogoCarousel*
 */
type LogoCarouselSliceVariation = LogoCarouselSliceDefault;

/**
 * LogoCarousel Shared Slice
 *
 * - **API ID**: `logo_carousel`
 * - **Description**: LogoCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoCarouselSlice = prismic.SharedSlice<
  "logo_carousel",
  LogoCarouselSliceVariation
>;

/**
 * Item in *Faq → Default → Primary → Buttons*
 */
export interface QuestionsSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Faq → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Variant field in *Faq → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary" | "Link">;
}

/**
 * Item in *Faq → Default → Primary → FAQs*
 */
export interface QuestionsSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *Faq → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface QuestionsSliceDefaultPrimary {
  /**
   * With divider field in *Faq → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.default.primary.with_border
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_border: prismic.BooleanField;

  /**
   * No background field in *Faq → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.default.primary.no_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  no_background: prismic.BooleanField;

  /**
   * Top Padding field in *Faq → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Faq → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Description image field in *Faq → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.description_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  description_image: prismic.ImageField<never>;

  /**
   * Buttons field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<
    Simplify<QuestionsSliceDefaultPrimaryButtonsItem>
  >;

  /**
   * FAQs field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<QuestionsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuestionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type QuestionsSliceVariation = QuestionsSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `questions`
 * - **Description**: Questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSlice = prismic.SharedSlice<
  "questions",
  QuestionsSliceVariation
>;

/**
 * Item in *Results → Default → Primary → Results*
 */
export interface ResultsSliceDefaultPrimaryResultsItem {
  /**
   * Link field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Title field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Tag one field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].tag_one
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_one: prismic.KeyTextField;

  /**
   * Tag two field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].tag_two
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tag_two: prismic.KeyTextField;

  /**
   * Stat one field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].stat_one
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_one: prismic.KeyTextField;

  /**
   * Stat one description field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].stat_one_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_one_description: prismic.KeyTextField;

  /**
   * Stat two field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].stat_two
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_two: prismic.KeyTextField;

  /**
   * Stat two description field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].stat_two_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stat_two_description: prismic.KeyTextField;

  /**
   * Logo field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Logo inverse field in *Results → Default → Primary → Results*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[].logo_inverse
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_inverse: prismic.ImageField<never>;
}

/**
 * Item in *Results → Default → Primary → Buttons*
 */
export interface ResultsSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Results → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Variant field in *Results → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary" | "Link">;
}

/**
 * Primary content in *Results → Default → Primary*
 */
export interface ResultsSliceDefaultPrimary {
  /**
   * With divider field in *Results → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: results.default.primary.with_border
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_border: prismic.BooleanField;

  /**
   * No background field in *Results → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: results.default.primary.no_background
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  no_background: prismic.BooleanField;

  /**
   * Top Padding field in *Results → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Results → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Caption field in *Results → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Title field in *Results → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Results → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Results field in *Results → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.results[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  results: prismic.GroupField<Simplify<ResultsSliceDefaultPrimaryResultsItem>>;

  /**
   * Buttons field in *Results → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: results.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<ResultsSliceDefaultPrimaryButtonsItem>>;
}

/**
 * Default variation for Results Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResultsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ResultsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Results*
 */
type ResultsSliceVariation = ResultsSliceDefault;

/**
 * Results Shared Slice
 *
 * - **API ID**: `results`
 * - **Description**: Results
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ResultsSlice = prismic.SharedSlice<
  "results",
  ResultsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataStructuredDataItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataContactUsItem,
      SettingsDocumentDataRepeatableTypesItem,
      AllDocumentTypes,
      AbsSlice,
      AbsSliceDefaultPrimaryTilesItem,
      AbsSliceDefaultPrimaryButtonsItem,
      AbsSliceDefaultPrimary,
      AbsSliceVariation,
      AbsSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimaryButtonsItem,
      CtaSliceDefaultPrimary,
      CtaSliceFullWidthPrimaryButtonsItem,
      CtaSliceFullWidthPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceFullWidth,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LogoCarouselSlice,
      LogoCarouselSliceDefaultPrimaryImagesItem,
      LogoCarouselSliceDefaultPrimary,
      LogoCarouselSliceVariation,
      LogoCarouselSliceDefault,
      QuestionsSlice,
      QuestionsSliceDefaultPrimaryButtonsItem,
      QuestionsSliceDefaultPrimaryFaqsItem,
      QuestionsSliceDefaultPrimary,
      QuestionsSliceVariation,
      QuestionsSliceDefault,
      ResultsSlice,
      ResultsSliceDefaultPrimaryResultsItem,
      ResultsSliceDefaultPrimaryButtonsItem,
      ResultsSliceDefaultPrimary,
      ResultsSliceVariation,
      ResultsSliceDefault,
    };
  }
}
