// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | LogoCarouselSlice
  | CtaSlice
  | QuestionsSlice
  | HeroSlice;

/**
 * Item in *Page → Structured Data*
 */
export interface PageDocumentDataStructuredDataItem {
  /**
   * JSON field in *Page → Structured Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.structured_data[].json
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  json: prismic.KeyTextField;
}

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Parent field in *Page*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: page.parent
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  parent: prismic.ContentRelationshipField<"page">;

  /**
   * Search Summary field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: This is used only for site search
   * - **API ID Path**: page.search_summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_summary: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * OG Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left empty, meta title will be used
   * - **API ID Path**: page.og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OG Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left empty, meta description will be used
   * - **API ID Path**: page.og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * OG URL field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: If left empty, default page URL will be used
   * - **API ID Path**: page.og_url
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_url: prismic.KeyTextField; /**
   * Structured Data field in *Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: page.structured_data[]
   * - **Tab**: Structured Data
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  structured_data: prismic.GroupField<
    Simplify<PageDocumentDataStructuredDataItem>
  >;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Contact Us*
 */
export interface SettingsDocumentDataContactUsItem {
  /**
   * Label field in *Settings → Contact Us*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us[].label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  label: prismic.RichTextField;

  /**
   * Icon Name field in *Settings → Contact Us*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;
}

/**
 * Item in *Settings → Repeatable Types*
 */
export interface SettingsDocumentDataRepeatableTypesItem {
  /**
   * Type field in *Settings → Repeatable Types*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The exact name of the page type
   * - **API ID Path**: settings.repeatable_types[].type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  type: prismic.KeyTextField;

  /**
   * Items per page field in *Settings → Repeatable Types*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_types[].items_per_page
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  items_per_page: prismic.NumberField;

  /**
   * Listing Page field in *Settings → Repeatable Types*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_types[].listing_page
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  listing_page: ContentRelationshipFieldWithData<
    [
      {
        id: "page";
        fields: [
          {
            id: "parent";
            customtypes: [{ id: "page"; fields: ["parent", "title"] }];
          },
          "title",
        ];
      },
    ]
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Title of the site
   * - **API ID Path**: settings.siteTitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  siteTitle: prismic.RichTextField;

  /**
   * Header Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.header_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  header_logo: prismic.ImageField<never>;

  /**
   * Footer Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  footer_logo: prismic.ImageField<never>;

  /**
   * GTM Code field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.gtm_code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gtm_code: prismic.KeyTextField;

  /**
   * Copyright Text field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;

  /**
   * Footer Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer_description: prismic.KeyTextField; /**
   * Social Profiles field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social_profiles
   * - **Tab**: Social Profiles
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_profiles: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      | "X (Twitter)"
      | "Facebook"
      | "LinkedIn"
      | "Instagram"
      | "TikTok"
      | "YouTube"
    >
  >; /**
   * Meta Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_title
   * - **Tab**: Default Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Default Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField; /**
   * Contact Us Title field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us_title
   * - **Tab**: Contact Details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_us_title: prismic.RichTextField;

  /**
   * Contact Us field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_us[]
   * - **Tab**: Contact Details
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_us: prismic.GroupField<
    Simplify<SettingsDocumentDataContactUsItem>
  >; /**
   * Repeatable Types field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.repeatable_types[]
   * - **Tab**: Repeatable Types
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repeatable_types: prismic.GroupField<
    Simplify<SettingsDocumentDataRepeatableTypesItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *Cta → Default → Primary → Buttons*
 */
export interface CtaSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon Name field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * Icon Alignment  field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].icon_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_alignment: prismic.SelectField<"Left" | "Right">;

  /**
   * Variant field in *Cta → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary">;
}

/**
 * Item in *Cta → Full Width → Primary → Buttons*
 */
export interface CtaSliceFullWidthPrimaryButtonsItem {
  /**
   * Link field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon Name field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * Icon Alignment  field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].icon_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_alignment: prismic.SelectField<"Left" | "Right">;

  /**
   * Variant field in *Cta → Full Width → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary">;
}

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Top Padding field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Cta → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * With Background Color field in *Cta → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: cta.default.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<CtaSliceDefaultPrimaryButtonsItem>>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Full Width → Primary*
 */
export interface CtaSliceFullWidthPrimary {
  /**
   * Top Padding field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Title field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Full Width → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.fullWidth.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<CtaSliceFullWidthPrimaryButtonsItem>>;
}

/**
 * Full Width variation for Cta Slice
 *
 * - **API ID**: `fullWidth`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceFullWidth = prismic.SharedSliceVariation<
  "fullWidth",
  Simplify<CtaSliceFullWidthPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault | CtaSliceFullWidth;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Buttons*
 */
export interface HeroSliceDefaultPrimaryButtonsItem {
  /**
   * Link field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Variant field in *Hero → Default → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary" | "Link">;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Top Padding field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Caption field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  caption: prismic.RichTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Text align left field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.text_align_left
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  text_align_left: prismic.BooleanField;

  /**
   * Buttons field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryButtonsItem>>;

  /**
   * CTA Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_description: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *LogoCarousel → Default → Primary → Images*
 */
export interface LogoCarouselSliceDefaultPrimaryImagesItem {
  /**
   * Image field in *LogoCarousel → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogoCarousel → Default → Primary*
 */
export interface LogoCarouselSliceDefaultPrimary {
  /**
   * Top Padding field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half">;

  /**
   * Bottom Padding field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half">;

  /**
   * With Background Color field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_carousel.default.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Title field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Full Width? field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_carousel.default.primary.full_width
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  full_width: prismic.BooleanField;

  /**
   * Fade Effect? field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_carousel.default.primary.fade_effect
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  fade_effect: prismic.BooleanField;

  /**
   * Two rows? field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: logo_carousel.default.primary.two_rows
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  two_rows: prismic.BooleanField;

  /**
   * Images field in *LogoCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo_carousel.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<LogoCarouselSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for LogoCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LogoCarousel*
 */
type LogoCarouselSliceVariation = LogoCarouselSliceDefault;

/**
 * LogoCarousel Shared Slice
 *
 * - **API ID**: `logo_carousel`
 * - **Description**: LogoCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoCarouselSlice = prismic.SharedSlice<
  "logo_carousel",
  LogoCarouselSliceVariation
>;

/**
 * Item in *Questions → Default → Primary → FAQs*
 */
export interface QuestionsSliceDefaultPrimaryFaqsItem {
  /**
   * Question field in *Questions → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Questions → Default → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Questions → Variation 2 → Primary → Buttons*
 */
export interface QuestionsSliceVariation2PrimaryButtonsItem {
  /**
   * Link field in *Questions → Variation 2 → Primary → Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Icon Name field in *Questions → Variation 2 → Primary → Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.buttons[].icon_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon_name: prismic.KeyTextField;

  /**
   * Icon Alignment field in *Questions → Variation 2 → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.buttons[].icon_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon_alignment: prismic.SelectField<"Left" | "Right">;

  /**
   * Variant field in *Questions → Variation 2 → Primary → Buttons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.buttons[].variant
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  variant: prismic.SelectField<"Primary" | "Secondary" | "Link">;
}

/**
 * Item in *Questions → Variation 2 → Primary → FAQs*
 */
export interface QuestionsSliceVariation2PrimaryFaqsItem {
  /**
   * Question field in *Questions → Variation 2 → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Questions → Variation 2 → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Questions → Variation 3 → Primary → FAQs*
 */
export interface QuestionsSliceVariation3PrimaryFaqsItem {
  /**
   * Question field in *Questions → Variation 3 → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Questions → Variation 3 → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Questions → Variation 4 → Primary → FAQs*
 */
export interface QuestionsSliceVariation4PrimaryFaqsItem {
  /**
   * Question field in *Questions → Variation 4 → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.faqs[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Questions → Variation 4 → Primary → FAQs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.faqs[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Questions → Default → Primary*
 */
export interface QuestionsSliceDefaultPrimary {
  /**
   * Top Padding field in *Questions → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Questions → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * With Background Color field in *Questions → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.default.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Subtitle field in *Questions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *Questions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Questions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * FAQs field in *Questions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.default.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<QuestionsSliceDefaultPrimaryFaqsItem>>;
}

/**
 * Default variation for Questions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuestionsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Questions → Variation 2 → Primary*
 */
export interface QuestionsSliceVariation2Primary {
  /**
   * Top Padding field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * With Background Color field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.variation2.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Subtitle field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<
    Simplify<QuestionsSliceVariation2PrimaryButtonsItem>
  >;

  /**
   * FAQs field in *Questions → Variation 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation2.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<QuestionsSliceVariation2PrimaryFaqsItem>>;
}

/**
 * Variation 2 variation for Questions Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<QuestionsSliceVariation2Primary>,
  never
>;

/**
 * Primary content in *Questions → Variation 3 → Primary*
 */
export interface QuestionsSliceVariation3Primary {
  /**
   * Top Padding field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * With Background Color field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.variation3.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Subtitle field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * FAQs field in *Questions → Variation 3 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation3.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<QuestionsSliceVariation3PrimaryFaqsItem>>;
}

/**
 * Variation 3 variation for Questions Slice
 *
 * - **API ID**: `variation3`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSliceVariation3 = prismic.SharedSliceVariation<
  "variation3",
  Simplify<QuestionsSliceVariation3Primary>,
  never
>;

/**
 * Primary content in *Questions → Variation 4 → Primary*
 */
export interface QuestionsSliceVariation4Primary {
  /**
   * Top Padding field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.top_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  top_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * Bottom Padding field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.bottom_padding
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  bottom_padding: prismic.SelectField<"Full" | "Half" | "None">;

  /**
   * With Background Color field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: questions.variation4.primary.with_background_color
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_background_color: prismic.BooleanField;

  /**
   * Subtitle field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * FAQs field in *Questions → Variation 4 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: questions.variation4.primary.faqs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faqs: prismic.GroupField<Simplify<QuestionsSliceVariation4PrimaryFaqsItem>>;
}

/**
 * Variation 4 variation for Questions Slice
 *
 * - **API ID**: `variation4`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSliceVariation4 = prismic.SharedSliceVariation<
  "variation4",
  Simplify<QuestionsSliceVariation4Primary>,
  never
>;

/**
 * Slice variation for *Questions*
 */
type QuestionsSliceVariation =
  | QuestionsSliceDefault
  | QuestionsSliceVariation2
  | QuestionsSliceVariation3
  | QuestionsSliceVariation4;

/**
 * Questions Shared Slice
 *
 * - **API ID**: `questions`
 * - **Description**: Questions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QuestionsSlice = prismic.SharedSlice<
  "questions",
  QuestionsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PageDocumentDataStructuredDataItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataContactUsItem,
      SettingsDocumentDataRepeatableTypesItem,
      AllDocumentTypes,
      CtaSlice,
      CtaSliceDefaultPrimaryButtonsItem,
      CtaSliceDefaultPrimary,
      CtaSliceFullWidthPrimaryButtonsItem,
      CtaSliceFullWidthPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceFullWidth,
      HeroSlice,
      HeroSliceDefaultPrimaryButtonsItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LogoCarouselSlice,
      LogoCarouselSliceDefaultPrimaryImagesItem,
      LogoCarouselSliceDefaultPrimary,
      LogoCarouselSliceVariation,
      LogoCarouselSliceDefault,
      QuestionsSlice,
      QuestionsSliceDefaultPrimaryFaqsItem,
      QuestionsSliceDefaultPrimary,
      QuestionsSliceVariation2PrimaryButtonsItem,
      QuestionsSliceVariation2PrimaryFaqsItem,
      QuestionsSliceVariation2Primary,
      QuestionsSliceVariation3PrimaryFaqsItem,
      QuestionsSliceVariation3Primary,
      QuestionsSliceVariation4PrimaryFaqsItem,
      QuestionsSliceVariation4Primary,
      QuestionsSliceVariation,
      QuestionsSliceDefault,
      QuestionsSliceVariation2,
      QuestionsSliceVariation3,
      QuestionsSliceVariation4,
    };
  }
}
