import { Instrument_Serif } from "next/font/google";
import localFont from "next/font/local";
import "./assets/css/globals.scss";

const InstrumentSerif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-instrument-serif",
});

const HelveticaNeue = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeueThin.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueThinItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueMediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "./fonts/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueBoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-helvetica-neue",
});

export const metadata = {
  title: "Absoliq",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${HelveticaNeue.variable} ${InstrumentSerif.variable}`}>
        {children}
      </body>
    </html>
  );
}
