// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  abs: dynamic(() => import("./Abs")),
  cta: dynamic(() => import("./Cta")),
  hero: dynamic(() => import("./Hero")),
  logo_carousel: dynamic(() => import("./LogoCarousel")),
  questions: dynamic(() => import("./Faq")),
  results: dynamic(() => import("./Results")),
};
