// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  abs: dynamic(() => import("./Abs")),
  comparison_and_testimonial: dynamic(
    () => import("./ComparisonAndTestimonial"),
  ),
  cta: dynamic(() => import("./Cta")),
  expertise: dynamic(() => import("./Expertise")),
  forms: dynamic(() => import("./Forms")),
  growing_tiles: dynamic(() => import("./GrowingTiles")),
  hero: dynamic(() => import("./Hero")),
  how_we_work: dynamic(() => import("./HowWeWork")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  logo_carousel: dynamic(() => import("./LogoCarousel")),
  questions: dynamic(() => import("./Faq")),
  results: dynamic(() => import("./Results")),
};
